### ISSUE TITLE
failure get less than 1 eligible file

### ISSUE THREAD

**Issue by tanpengsccd** [zhangruiyu/FlutterJsonBeanFactory#17]
![image](https://user-images.githubusercontent.com/13959880/57361827-e7949280-71af-11e9-9764-fd7405acb75c.png)
产生错误信息

**Comment by tanpengsccd** [comment]
JSON 

{
    "id": "QXJpYU5nXzE1NTcwNDE5MzdfMC4xMTk5MDc2NTM4NjM5MTE2Nw==",
    "jsonrpc": "2.0",
    "result": [
        {
            "bitfield": "00",
            "bittorrent": {
                "announceList": [
                    [
                        "udp://9.rarbg.to:2710/announce"
                    ],
                    [
                        "udp://9.rarbg.me:2710/announce"
                    ],
                    [
                        "http://tr.cili001.com:8070/announce"
                    ],
                    [
                        "http://tracker.trackerfix.com:80/announce"
                    ],
                    [
                        "udp://open.demonii.com:1337"
                    ],
                    [
                        "udp://tracker.opentrackr.org:1337/announce"
                    ],
                    [
                        "udp://p4p.arenabg.com:1337"
                    ],
                    [
                        "udp://9.rarbg.com:2710/announce"
                    ],
                    [
                        "udp://tracker.skyts.net:6969/announce"
                    ],
                    [
                        "udp://tracker.safe.moe:6969/announce"
                    ],
                    [
                        "udp://tracker.piratepublic.com:1337/announce"
                    ],
                    [
                        "udp://tracker.pirateparty.gr:6969/announce"
                    ],
                    [
                        "udp://tracker.coppersurfer.tk:6969/announce"
                    ],
                    [
                        "udp://tracker.leechers-paradise.org:6969/announce"
                    ],
                    [
                        "udp://allesanddro.de:1337/announce"
                    ],
                    [
                        "udp://p4p.arenabg.com:1337/announce"
                    ],
                    [
                        "udp://tracker.opentrackr.org:1337/announce"
                    ],
                    [
                        "udp://public.popcorn-tracker.org:6969/announce"
                    ],
                    [
                        "udp://wambo.club:1337/announce"
                    ],
                    [
                        "udp://trackerxyz.tk:1337/announce"
                    ],
                    [
                        "udp://tracker4.itzmx.com:2710/announce"
                    ],
                    [
                        "udp://tracker2.christianbro.pw:6969/announce"
                    ],
                    [
                        "udp://tracker1.xku.tv:6969/announce"
                    ],
                    [
                        "udp://tracker1.wasabii.com.tw:6969/announce"
                    ],
                    [
                        "udp://tracker.zer0day.to:1337/announce"
                    ]
                ]
            },
            "completedLength": "0",
            "connections": "47",
            "dir": "/Users/tanpengsccd/Downloads",
            "downloadSpeed": "0",
            "files": [
                {
                    "completedLength": "0",
                    "index": "1",
                    "length": "29538",
                    "path": "[METADATA]复仇者联盟2.1080p.720p.国英双语.BD中英双字",
                    "selected": "true",
                    "uris": []
                }
            ],
            "gid": "596af1afb2442292",
            "infoHash": "aaffe4c6b800e28a9e2557dc0e169c6d34340f43",
            "numPieces": "2",
            "numSeeders": "0",
            "pieceLength": "16384",
            "seeder": "false",
            "status": "active",
            "totalLength": "29538",
            "uploadLength": "0",
            "uploadSpeed": "0"
        },
        {
            "bitfield": "00",
            "bittorrent": {
                "announceList": [
                    [
                        "udp://9.rarbg.to:2710/announce"
                    ],
                    [
                        "udp://9.rarbg.me:2710/announce"
                    ],
                    [
                        "http://tr.cili001.com:8070/announce"
                    ],
                    [
                        "http://tracker.trackerfix.com:80/announce"
                    ],
                    [
                        "udp://open.demonii.com:1337"
                    ],
                    [
                        "udp://tracker.opentrackr.org:1337/announce"
                    ],
                    [
                        "udp://p4p.arenabg.com:1337"
                    ],
                    [
                        "udp://9.rarbg.com:2710/announce"
                    ],
                    [
                        "udp://tracker.skyts.net:6969/announce"
                    ],
                    [
                        "udp://tracker.safe.moe:6969/announce"
                    ],
                    [
                        "udp://tracker.piratepublic.com:1337/announce"
                    ],
                    [
                        "udp://tracker.pirateparty.gr:6969/announce"
                    ],
                    [
                        "udp://tracker.coppersurfer.tk:6969/announce"
                    ],
                    [
                        "udp://tracker.leechers-paradise.org:6969/announce"
                    ],
                    [
                        "udp://allesanddro.de:1337/announce"
                    ],
                    [
                        "udp://p4p.arenabg.com:1337/announce"
                    ],
                    [
                        "udp://tracker.opentrackr.org:1337/announce"
                    ],
                    [
                        "udp://public.popcorn-tracker.org:6969/announce"
                    ],
                    [
                        "udp://wambo.club:1337/announce"
                    ],
                    [
                        "udp://trackerxyz.tk:1337/announce"
                    ],
                    [
                        "udp://tracker4.itzmx.com:2710/announce"
                    ],
                    [
                        "udp://tracker2.christianbro.pw:6969/announce"
                    ],
                    [
                        "udp://tracker1.xku.tv:6969/announce"
                    ],
                    [
                        "udp://tracker1.wasabii.com.tw:6969/announce"
                    ],
                    [
                        "udp://tracker.zer0day.to:1337/announce"
                    ]
                ]
            },
            "completedLength": "0",
            "connections": "42",
            "dir": "/Users/tanpengsccd/Downloads",
            "downloadSpeed": "0",
            "files": [
                {
                    "completedLength": "0",
                    "index": "1",
                    "length": "24505",
                    "path": "[METADATA]驯龙高手3.1080p.720p.国英双语.BD中英双字",
                    "selected": "true",
                    "uris": []
                }
            ],
            "gid": "e03cd843cc5d6c9f",
            "infoHash": "313cfba88f2055c72c19869a35012453774a36a4",
            "numPieces": "2",
            "numSeeders": "0",
            "pieceLength": "16384",
            "seeder": "false",
            "status": "active",
            "totalLength": "24505",
            "uploadLength": "0",
            "uploadSpeed": "0"
        }
    ]
}

**Comment by tanpengsccd** [comment]
Android Studio 3.4
Build #AI-183.5429.30.34.5452501, built on April 10, 2019
JRE: 1.8.0_152-release-1343-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4

**Comment by tanpengsccd** [comment]
简单JSON
```
{
    "jsonrpc": "2.0",
    "method": "aria2.tellActive",
    "id": "QXJpYU5nXzE1NTcwNDE5MzdfMC4xMTk5MDc2NTM4NjM5MTE2Nw==",
    "params":[]
}
```
不会报错，却无法生成对应文件

**Comment by zhangruiyu** [comment]
已经修复了,需要审核,可以暂时下载https://github.com/zhangruiyu/FlutterJsonBeanFactory/blob/master/FlutterJsonBeanFactory.zip,然后idea安装本地的包

**Comment by tanpengsccd** [comment]
v2.2 依然不能生成。
![image](https://user-images.githubusercontent.com/13959880/57422325-312dbd80-7242-11e9-9b55-5f27a36ea687.png)

**Comment by zhangruiyu** [comment]
> v2.2 依然不能生成。
> ![image](https://user-images.githubusercontent.com/13959880/57422325-312dbd80-7242-11e9-9b55-5f27a36ea687.png)

加下qq说吧 157418979 问题随便填
