### ISSUE TITLE
Error occurred when try casting null to List<String> 

### ISSUE THREAD

**Issue by yrom** [zhangruiyu/FlutterJsonBeanFactory#18]
JSON:
```
{
"list": ["1", "2", "3"],
}
```

generated dart code:

```
list = json['list'].cast<String>()
```

Boom if `json['list']` is null

Workaround: 
```
list = json['list']?.cast<String>()
```

**Comment by zhangruiyu** [comment]
This issue has been fixed and is now under review. You can download the link below
https://github.com/zhangruiyu/FlutterJsonBeanFactory/blob/master/FlutterJsonBeanFactory.zip
