### ISSUE TITLE
文件名大小写不敏感，二级Map或List的Class名没有加上文件名

### ISSUE THREAD

**Issue by Vidtion** [zhangruiyu/FlutterJsonBeanFactory#2]
比如这样一个json：
`{
    "Total":1,
    "StartIndex":0,
    "Count":1,
    "Items":[
        {
            "Id":"2f5bc029-3042-47d0-af17-a8e700ad181d",
            "ServiceCode":"999999"
        }
    ]
}`
Class Name取 ServerConfig
期望生成的文件主类名为ServerConfigEntity，实际生成为ServerconfigEntity（大小写不敏感）。 
json中Items字段对应的类名期望是ServerConfigItem，实际为Items。
其他问题不大，插件挺好用，感谢作者。

**Comment by zhangruiyu** [comment]
emmm,那我给所以的二级class都加上一级文件名选项

**Comment by zhangruiyu** [comment]
可以填server_config就会生成了,比较官方用的是下划线样式

**Comment by zhangruiyu** [comment]
毕竟

**Comment by zhangruiyu** [comment]
可以填server_config就会生成了,毕竟官方用的是下划线样式

**Comment by zhangruiyu** [comment]
嗯 我会综合修改

**Comment by zhangruiyu** [comment]
明天修复二级class问题..

**Comment by zhangruiyu** [comment]
![image](https://user-images.githubusercontent.com/10591822/52389667-876a5380-2acf-11e9-9d67-1d078dffdf60.png)

**Comment by zhangruiyu** [comment]
![image](https://user-images.githubusercontent.com/10591822/52389679-9c46e700-2acf-11e9-94a8-a5f61ca88496.png)

**Comment by Vidtion** [comment]
再提个建议：
期望：List<ServerConfigItem> items;
实际：List<ServerConfigItem> item;
也就是List字段的类名去除s，但是属性保留s。
