### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by shui4** [zhangruiyu/FlutterJsonBeanFactory#20]
用了很多和这个类似的插件，我感觉这个特别好用，生成Factory，很贴心，就是int类型，要手动换成double，有点麻烦，希望作者后面能完善一下识别int还是double的类型，实在不行的话，可以试试把int换成var。
建议作者去看看json_serializable这个插件，看看能不能结合在一起，如果可以就真的太棒了

**Comment by zhangruiyu** [comment]
会考虑的  不过我现在在搞一个自己app 暂时不会修改这个东西了

**Comment by zhangruiyu** [comment]
目前已经更新到3.1,但是在审核中 可以再次尝试
