### ISSUE TITLE
希望加个功能，生成后的entity，修改了字段，能重新生成下

### ISSUE THREAD

**Issue by fengdesola** [zhangruiyu/FlutterJsonBeanFactory#21]
希望加个功能，生成后的entity，修改了字段，能重新生成下

**Comment by zhangruiyu** [comment]
啊 不太明白啊

**Comment by fengdesola** [comment]
就是对象已经有了，改了字段名字或者新增了字段，那fromJson等方法就不对了，希望能通过类的字段，重新生成fromJson等方法

**Comment by zhangruiyu** [comment]
我有想法 但是没时间去实现 之前考虑过这个问题  具体就生成一个伴生类 这个类会有个快捷键去根据实体类生成 不过没时间去搞 闲下来了 去搞

**Comment by fengdesola** [comment]
哦哦，辛苦了

**Comment by zhangruiyu** [comment]
目前已经更新到3.1,但是在审核中 大概明天可以再次尝试
