### ISSUE TITLE
修改完字段怎么重新生成文件啊，commend+"没有效果

### ISSUE THREAD

**Issue by zhengcx** [zhangruiyu/FlutterJsonBeanFactory#24]
快捷键不好使，不同电脑IDE快捷键容易冲突。还有建议能不能支持自己手写的model帮忙生成generated下的文件

**Comment by zhangruiyu** [comment]
新加字段是支持的，目前最新版本是支持的，快捷键实在想不到啥好用了，给个建议哈。
 
---原始邮件---
发件人: "DavidSu"<notifications@github.com&gt;
发送时间: 2019年12月28日 13:01:49
收件人: "zhangruiyu/FlutterJsonBeanFactory"<FlutterJsonBeanFactory@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [zhangruiyu/FlutterJsonBeanFactory] 修改完字段怎么重新生成文件啊，commend+"没有效果 (#24)



快捷键不好使，不同电脑IDE快捷键容易冲突。还有建议能不能支持自己手写的model帮忙生成generated下的文件

**Comment by zhangruiyu** [comment]
https://github.com/zhangruiyu/FlutterJsonBeanFactory/releases 3.1.5已经修改快捷键为alt + j,重新生成只需要添加字段,然后按下alt + j就好

**Comment by zhangruiyu** [comment]
目前3.1.5已经修改快捷键为alt + j

**Comment by RunningTheSnail** [comment]
windows 快捷键是什么啊

**Comment by RunningTheSnail** [comment]
> 目前3.1.5已经修改快捷键为alt + j

windows 快捷键是什么啊
