### ISSUE TITLE
json 转 model 错误

### ISSUE THREAD

**Issue by luoei** [zhangruiyu/FlutterJsonBeanFactory#25]
Android Studio ： 3.5.3
Flutter: V42.1.1
Dart: V191.8593
FlutterJsonBeanFactory： v3.1.3-191
本地flutter : 1.12.13
本地dart：2.7

json：

`{
	"code": 0,
	"msg": "成功",
	"data": {
		"commentList": [""],
		"originalPrice": 0,
		"reviewIntroductionList": [],
		"openDay": "2019/12/23 00:00:00",
		"fn": 0,
		"learningPeriod": {
			"beginTime": "2019/12/30 00:00:00",
			"endTime": "2020/01/03 00:00:00"
		},
		"title": "测试20191223",
		"bigbayUrl": "",
		"staffList": [{
			"id": 4,
			"nickName": "美女辅导员",
			"photo": "",
			"role": "助教",
			"createTime": "2019/06/20 12:10:48",
			"modifyTime": "2019/06/20 12:10:48"
		}, {
			"id": 1,
			"nickName": "江珊",
			"photo": "",
			"role": "高级辅导员",
			"createTime": "2019/04/03 16:47:59",
			"modifyTime": "2019/04/29 20:12:24"
		}],
		"applePrice": 0,
		"termId": "xx",
		"payType": 0,
		"price": 0,
		"lessonServiceList": ["xxx"],
		"beginTime": "2019/12/23 00:00:00",
		"expiryDay": 20,
		"wechatName": "这里是微信号",
		"courseId": "c_f81642280",
		"productType": "term",
		"image": "xxxx",
		"productId": "",
		"downloadInformationUrl": "xxxx",
		"lessonCount": 5,
		"isFollow": true,
		"introductionList": ["xxx"],
		"shareTitle": "不看后悔哦！",
		"wechatImage": "xxx",
		"shareUrl": "xxx",
		"endTime": "2019/12/29 00:00:00",
		"slogan": "这里是",
		"needAddress": 1
	}
}`

**Comment by zhangruiyu** [comment]
等等插件审核，明天我再看看，.3版本有bug，但是美国那边他们放假了


 
---原始邮件---
发件人: "Luoei"<notifications@github.com&gt;
发送时间: 2019年12月28日 17:35:54
收件人: "zhangruiyu/FlutterJsonBeanFactory"<FlutterJsonBeanFactory@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [zhangruiyu/FlutterJsonBeanFactory] json 转 model 错误 (#25)



Android Studio ： 3.5.3
 Flutter: V42.1.1
 Dart: V191.8593
 FlutterJsonBeanFactory： v3.1.3-191
 本地flutter : 1.12.13
 本地dart：2.7
 
json：
 
{ "code": 0, "msg": "成功", "data": { "commentList": [""], "originalPrice": 0, "reviewIntroductionList": [], "openDay": "2019/12/23 00:00:00", "fn": 0, "learningPeriod": { "beginTime": "2019/12/30 00:00:00", "endTime": "2020/01/03 00:00:00" }, "title": "测试20191223", "bigbayUrl": "", "staffList": [{ "id": 4, "nickName": "美女辅导员", "photo": "", "role": "助教", "createTime": "2019/06/20 12:10:48", "modifyTime": "2019/06/20 12:10:48" }, { "id": 1, "nickName": "江珊", "photo": "", "role": "高级辅导员", "createTime": "2019/04/03 16:47:59", "modifyTime": "2019/04/29 20:12:24" }], "applePrice": 0, "termId": "xx", "payType": 0, "price": 0, "lessonServiceList": ["xxx"], "beginTime": "2019/12/23 00:00:00", "expiryDay": 20, "wechatName": "这里是微信号", "courseId": "c_f81642280", "productType": "term", "image": "xxxx", "productId": "", "downloadInformationUrl": "xxxx", "lessonCount": 5, "isFollow": true, "introductionList": ["xxx"], "shareTitle": "不看后悔哦！", "wechatImage": "xxx", "shareUrl": "xxx", "endTime": "2019/12/29 00:00:00", "slogan": "这里是", "needAddress": 1 } }

**Comment by luoei** [comment]
> 等等插件审核，明天我再看看，.3版本有bug，但是美国那边他们放假了
> […](#)

好勒，更新了的话，这里回复一下哈，我好更新插件。

非常感谢作者辛勤付出。

**Comment by zhangruiyu** [comment]
> > 等等插件审核，明天我再看看，.3版本有bug，但是美国那边他们放假了
> > […](#)
> 
> 好勒，更新了的话，这里回复一下哈，我好更新插件。
> 
> 非常感谢作者辛勤付出。

上面已经修复了 我还没发不 加个qq好友吧
157418979 问题随便填  我想了解下studio问题

**Comment by luoei** [comment]
> > > 等等插件审核，明天我再看看，.3版本有bug，但是美国那边他们放假了
> > > […](#)
> > 
> > 
> > 好勒，更新了的话，这里回复一下哈，我好更新插件。
> > 非常感谢作者辛勤付出。
> 
> 上面已经修复了 我还没发不 加个qq好友吧
> 157418979 问题随便填 我想了解下studio问题

哥们，QQ号码提示问题验证错误，我输入zhangruiyu/ruiyu/张瑞宇/瑞宇 都不行

**Comment by zhangruiyu** [comment]
那你留吧 加你 我也忘记了问题是啥了

**Comment by zhangruiyu** [comment]
> > > > 等等插件审核，明天我再看看，.3版本有bug，但是美国那边他们放假了
> > > > […](#)
> > > 
> > > 
> > > 好勒，更新了的话，这里回复一下哈，我好更新插件。
> > > 非常感谢作者辛勤付出。
> > 
> > 
> > 上面已经修复了 我还没发不 加个qq好友吧
> > 157418979 问题随便填 我想了解下studio问题
> 
> 哥们，QQ号码提示问题验证错误，我输入zhangruiyu/ruiyu/张瑞宇/瑞宇 都不行

那你留吧 加你 我也忘记了问题是啥了

**Comment by luoei** [comment]
> > > > > 等等插件审核，明天我再看看，.3版本有bug，但是美国那边他们放假了
> > > > > […](#)
> > > > 
> > > > 
> > > > 好勒，更新了的话，这里回复一下哈，我好更新插件。
> > > > 非常感谢作者辛勤付出。
> > > 
> > > 
> > > 上面已经修复了 我还没发不 加个qq好友吧
> > > 157418979 问题随便填 我想了解下studio问题
> > 
> > 
> > 哥们，QQ号码提示问题验证错误，我输入zhangruiyu/ruiyu/张瑞宇/瑞宇 都不行
> 
> 那你留吧 加你 我也忘记了问题是啥了

373307094
