### ISSUE TITLE
This project is not flutter

### ISSUE THREAD

**Issue by luoei** [zhangruiyu/FlutterJsonBeanFactory#26]
如果项目是Android集成flutter进行开发，走的是源码依赖，点击"build" -> "FlutterBeanFactory" 就会提示：This project is not flutter。如果单独打开flutter项目，这么做是没有问题。对于集成的项目，这个有啥好办法吗？ 平时开发是打开Android项目，切换源码导航视图为"project"，就可以看到fluter 项目。

**Comment by zhangruiyu** [comment]
emmm .需要的话，我可以把这个判断去掉


 
---Original---

**Comment by luoei** [comment]
> emmm .需要的话，我可以把这个判断去掉
> […](#)

很需要哈，目前用的插件是2.7的版本，但不灵活，服务端添加字段啥的，就需要用json重新生成，3.x的版本，需要单独打开flutter项目去生成，在团队协作中，需要和其它伙伴沟通，有点不太友好，能支持非flutter项目生成是就最好了，非常感谢作者辛勤付出。

**Comment by zhangruiyu** [comment]
https://github.com/zhangruiyu/FlutterJsonBeanFactory/releases 3.1.5已经修复这个问题
