### ISSUE TITLE
DateTime类型的时候生成的代码有问题，希望优化一下，不然每次改动文件，重新生成的DateTime类型都不对，很烦

### ISSUE THREAD

**Issue by zhengcx** [zhangruiyu/FlutterJsonBeanFactory#27]

**Comment by zhangruiyu** [comment]
好的 一开始我没考虑去怼datetime类型做适配,下个版本我给加上  大概是3.1.6版本

**Comment by zhangruiyu** [comment]
已经支持了datetime,需要下次发版,大概这周内上线

**Comment by zhangruiyu** [comment]
https://github.com/zhangruiyu/FlutterJsonBeanFactory/releases 已经发包了,但是在审核,可以在release页面下载,从本地安装
