### ISSUE TITLE
/generated/json/base/json_filed.dart 文件自动生成

### ISSUE THREAD

**Issue by wjyconan** [zhangruiyu/FlutterJsonBeanFactory#28]
这个目录和文件总是自动生成，删除了马上又生成了，由于某些情况下不希望它自动生成，不知道是我插件的问题，还是就是设计成这样的，我希望能够在生成类或者factory的时候去生成这个类，现在任意项目中都会自动生成这个文件，即便我不用jsonBean，不知道我表达清楚了没有。

**Comment by zhangruiyu** [comment]
明白,我会在下个版本修复,目前想的就是在pubspec.yaml里配置一个选项,可以选择插件不启用,大致这样,默认不写则开启插件,写了false则在此项目不启用,觉得咋样
![image](https://user-images.githubusercontent.com/10591822/71574339-446c0100-2b23-11ea-9dd5-a7152182737b.png)

**Comment by zhangruiyu** [comment]
> 这个目录和文件总是自动生成，删除了马上又生成了，由于某些情况下不希望它自动生成，不知道是我插件的问题，还是就是设计成这样的，我希望能够在生成类或者factory的时候去生成这个类，现在任意项目中都会自动生成这个文件，即便我不用jsonBean，不知道我表达清楚了没有。
明白,我会在下个版本修复,目前想的就是在pubspec.yaml里配置一个选项,可以选择插件不启用,大致这样,默认不写则开启插件,写了false则在此项目不启用,觉得咋样
![image](https://user-images.githubusercontent.com/10591822/71574362-62396600-2b23-11ea-8030-2ed955195ef1.png)

**Comment by zhangruiyu** [comment]
https://github.com/zhangruiyu/FlutterJsonBeanFactory/releases 已经发包了,但是在审核,可以在release页面下载,从本地安装   目前修改为: 不默认生成,除非你使用快捷键生成,或者生成省的entity 使用方法
![image](https://user-images.githubusercontent.com/10591822/71607520-0cad9980-2bb5-11ea-9606-768aaaae5678.png)
