### ISSUE TITLE
跟以前版本完全不兼容。且新版生成成了这样。。。也没有generated相关

### ISSUE THREAD

**Issue by joker-fu** [zhangruiyu/FlutterJsonBeanFactory#30]
![21578033585_ pic](https://user-images.githubusercontent.com/20105457/71710495-7ccb5200-2e37-11ea-8d62-9617f7d9c53f.jpg)

![image](https://user-images.githubusercontent.com/20105457/71711619-c9655c00-2e3c-11ea-930a-fe1cbd5fa371.png)

**Comment by zhangruiyu** [comment]
老哥 qq号给我

**Comment by joker-fu** [comment]
770759502
