### ISSUE TITLE
关于List泛型 不知道有没有点帮助

### ISSUE THREAD

**Issue by joker-fu** [zhangruiyu/FlutterJsonBeanFactory#31]
![image](https://user-images.githubusercontent.com/20105457/71717450-1d7b3b00-2e53-11ea-94dc-2402f8b6b421.png)

![image](https://user-images.githubusercontent.com/20105457/71717508-48fe2580-2e53-11ea-97d6-c472ae2b7041.png)

![image](https://user-images.githubusercontent.com/20105457/71717531-5a473200-2e53-11ea-9b1d-1adee7355ae7.png)

**Comment by zhangruiyu** [comment]
有想法,但是用处不大,因为毕竟后台返回数据要一般都有外层{"code":0,"data":*}这样的最外层包裹,所以用处不大

**Comment by zhangruiyu** [comment]
具体实现直接判断泛型就可以list的泛型然后遍历就行  因为没这需求加上我本身毕竟懒 就没做

**Comment by zhangruiyu** [comment]
老哥  你给个qq或者加个群 我已经做好了
