### ISSUE TITLE
JSONField，好像有点问题

### ISSUE THREAD

**Issue by cuipengxiang** [zhangruiyu/FlutterJsonBeanFactory#32]
![1](https://user-images.githubusercontent.com/4444831/71758821-88725380-2edf-11ea-9636-12e78639e47f.jpg)
生成的时候把有下划线的字段转成了驼峰命名，自动添加了@JSONField批注，但是helper里面生成代码的时候好像有点问题。
使用的数据如下：
{
  "id": 2172,
  "uid": 1600,
  "orgid": 2,
  "remark": "",
  "tel": "6668279",
  "accounttitle": "中国烟台人力资源服务产业园",
  "accountid": "",
  "realname": "刘明强",
  "company": "芝罘区创业培训中心",
  "com_address": "华茂街30号",
  "addtime": "",
  "fans": "",
  "operations": "",
  "piece": "",
  "isauthentication": "0",
  "political": 0,
  "job": "",
  "email": "zfqjyb@sina.com",
  "qq": "",
  "url": "",
  "image": "",
  "isPublic": "Y",
  "status": 1,
  "create_ip": "218.56.36.228",
  "create_time": 1578037921,
  "modify_time": 1578037921,
  "modify_ip": "218.56.36.228",
  "account": "15864068888",
  "password": "635e9dce2c80bf7d8757119",
  "regionid": 2,
  "type": "0",
  "last_login_time": 1578036979,
  "last_login_ip": "101.91.60.106",
  "delete_time": null,
  "org_name": "微信公众号",
  "regionname": "芝罘区"
}
另外，tel 字段的类型好像判断的不对
![2](https://user-images.githubusercontent.com/4444831/71758906-4269bf80-2ee0-11ea-943f-2f803f8b4855.jpg)
![3](https://user-images.githubusercontent.com/4444831/71758907-45fd4680-2ee0-11ea-8a1c-a5b9d786db5e.jpg)

**Comment by zhangruiyu** [comment]
已经提交审核了，3.2.0，可以去release页面下载最新的

**Comment by liruqian** [comment]
![image](https://user-images.githubusercontent.com/25815927/71780196-66212880-2ffa-11ea-844d-aaf0125b1ca4.png)
字段用的大写也会出现这种错误呢

**Comment by zhangruiyu** [comment]
> ![image](https://user-images.githubusercontent.com/25815927/71780196-66212880-2ffa-11ea-844d-aaf0125b1ca4.png)
> 字段用的大写也会出现这种错误呢

大写我测试了下 没发现问题,可取release页下载最新版本
