### ISSUE TITLE
model 转json有问题（3.2.7）

### ISSUE THREAD

**Issue by WangYan666** [zhangruiyu/FlutterJsonBeanFactory#33]
{
  "user": {
    "wang": {
      "name": ""
    }
  }
}

Map<String, dynamic> myTestUserToJson(MyTestUser entity) {
  final Map<String, dynamic> data = new Map<String, dynamic>();
  if (entity.wang != null) {
    
   /// 转json时 new了MyTestUserWang对象
    data['wang'] = MyTestUserWang().toJson();

    /// 应该是：
    data['wang'] = entity.wang.toJson();
  }
  return data;
}

**Comment by zhangruiyu** [comment]
哇 确实 有这个问题 感谢感谢

**Comment by zhangruiyu** [comment]
已修改 下次发版修复

**Comment by zhangruiyu** [comment]
![image](https://user-images.githubusercontent.com/10591822/72122592-5f4b3a80-3399-11ea-8195-54beca082d16.png)
改好了

**Comment by WangYan666** [comment]
{"names":["wy",{"key":"123"}]}，类似于这种结构，
我改为List<dynamic>类型：
class MyTestEntity with JsonConvert<MyTestEntity> {
  List<dynamic> names;
}
对应生成的helper如下，仍然会生成空的List
Map<String, dynamic> myTestEntityToJson(MyTestEntity entity) {
  final Map<String, dynamic> data = new Map<String, dynamic>();
  if (entity.names != null) {
    data['names'] = [];
  }
  return data;
}

**Comment by zhangruiyu** [comment]
说实话 我不知道这个json怎么解析了  目前对数组来说最基本的就是数组内类型一致

**Comment by zhangruiyu** [comment]
建议改map
