### ISSUE TITLE
不会生成 helper 文件

### ISSUE THREAD

**Issue by Adgeros** [zhangruiyu/FlutterJsonBeanFactory#34]
AS 不会自动生成 helper 文件
![微信截图_20200113164144](https://user-images.githubusercontent.com/16331459/72242130-99c80800-3623-11ea-90fb-ef69218590a4.png)

**Comment by zhangruiyu** [comment]
系统,和as版本号发一下

**Comment by Adgeros** [comment]
Android Studio 3.5.3
Build #AI-191.8026.42.35.6010548, built on November 15, 2019
JRE: 1.8.0_202-release-1483-b03 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by zhouyua3253** [comment]
求助，Idea 不生成helper.dart

macOS 10.15.2 

IntelliJ IDEA 2019.3.3 Preview (Ultimate Edition)
Build #IU-193.6494.1, built on January 28, 2020

**Comment by zhangruiyu** [comment]
加群说下 963752388  我这边是好的  细聊

**Comment by zhangruiyu** [comment]
删除.idea目录 然后重启开发工具
