### ISSUE TITLE
怎么新版本怎么才能同时解析多个字段呢？

### ISSUE THREAD

**Issue by EightMinuteYouth** [zhangruiyu/FlutterJsonBeanFactory#35]
有时候比较骚的后台可能会返回多个字段，类似time = json['create_time'] ?? json['order_time'] ?? json['borrowTime']，这时请问@JSONField可以供一个自持的api吗？

**Comment by zhangruiyu** [comment]
卧槽,这个就有点吊了 ,这是你们后台的锅, 怎么还要摔给移动端!目前来说 你在定义多个字段 String create_time,String order_time,String borrowTime, 然后自己判断取哪个吧
