### ISSUE TITLE
如何在当前版本不使用注解？3.3.1-191

### ISSUE THREAD

**Issue by fflin** [zhangruiyu/FlutterJsonBeanFactory#36]

**Comment by zhangruiyu** [comment]
加群说吧&nbsp; 不懂你的意思


 
---原始邮件---
发件人: "fflin"<notifications@github.com&gt;
发送时间: 2020年1月15日 19:38:23
收件人: "zhangruiyu/FlutterJsonBeanFactory"<FlutterJsonBeanFactory@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [zhangruiyu/FlutterJsonBeanFactory] 如何在当前版本不使用注解？3.3.1-191 (#36)
