### ISSUE TITLE
如果我单独使用国际化的sdk就不会生成helper

### ISSUE THREAD

**Issue by EightMinuteYouth** [zhangruiyu/FlutterJsonBeanFactory#37]
![image](https://user-images.githubusercontent.com/27809605/72504055-0c312600-3878-11ea-8c95-f2b4de03c36b.png)
如果单独使用下面这个国际化的sdk就不能生成helper文件

**Comment by zhangruiyu** [comment]
加群说吧   有点不大懂 为什么加个群 963752388
