### ISSUE TITLE
package:null/generated/json/base/json_convert_content.dart

### ISSUE THREAD

**Issue by rex26** [zhangruiyu/FlutterJsonBeanFactory#39]
1.ubuntu 18.04 + Android Studio 3.6 rc2
2.Project: Android modules+flutter module
3.json_convert_content.dart & *.helper unexist
4.entity file imported package:null/generated/json/base/json_convert_content.dart

**Comment by zfavourite99** [comment]
same problem.
1.macOS Catalina  10.15.2 + intellij idea 2019.3.2
2.Project: Flutter modules
3.json_convert_content.dart created in right clicked directory.
4.*.helper not exist
5.entity file imported package:null/generated/json/base/json_convert_content.dart

**Comment by zhangruiyu** [comment]
删除.idea目录 然后重启开发工具

**Comment by sanrixue** [comment]
没有作用 删除idea 创建package：null

**Comment by zhiyouhuihui240** [comment]
没有解决的吗、。？
