### ISSUE TITLE
Tried calling: toInt()

### ISSUE THREAD

**Issue by scsfwgy** [zhangruiyu/FlutterJsonBeanFactory#42]
`
NoSuchMethodError: Class 'String' has no instance method 'toInt'.
    Receiver: "86"
    Tried calling: toInt()
`

should use:json['code']?.toInt()=>int.parse(json['code'])

**Comment by zhangruiyu** [comment]
I think it's time to change the type of the code field, for example, to an int, or to ask your background developer for a change

**Comment by scsfwgy** [comment]
dart的json转换太麻烦了，并且还不能自动数据转换。“1”这种数据在java（gson）中用String、int、double都可以接收。是因为没有反射的原因吗？至于后端去改基本不现实，改动需要多端配合。一个模型转换能把人玩死...
