### ISSUE TITLE
怎么修改和删除？

### ISSUE THREAD

**Issue by aplixy** [zhangruiyu/FlutterJsonBeanFactory#50]
生成的类怎么安全删除？如果后台返回的Json数据有十几个字段有改变，应该怎么修改？能不能一键导入新的Json数据替换旧的？

**Comment by zhangruiyu** [comment]
文件删了重新生成吧 或者手动添加完字段后 快捷键重新生成

**Comment by aplixy** [comment]
> 文件删了重新生成吧 或者手动添加完字段后 快捷键重新生成

谢谢

**Comment by derekzhan** [comment]
windows下重新生成的快捷键是什么

**Comment by RunningTheSnail** [comment]
windows下重新生成的快捷键是什么
