### ISSUE TITLE
List嵌套List生成的helper类不正确

### ISSUE THREAD

**Issue by zhpoo** [zhangruiyu/FlutterJsonBeanFactory#51]
JSON:
{"code":200,"message":"成功","data":[["收款人名称","史蒂夫"],["收款人账号","123456789"],["收款银行代码","ABCD34"],["收款银行名称","ABCD银行"],["收款银行机构鉴定代码","1233443"],["收款银行地址","某城市"],["收款人地址","某城市"],["收款人电话","213214443"]]}

helper.dart:

![image](https://user-images.githubusercontent.com/20085147/81895659-5ab3be80-95e5-11ea-997b-89b227821701.png)

Android Studio 3.6.3
FlutterJsonBeanFactory 插件版本：3.7.0-192

**Comment by zhangruiyu** [comment]
list里只支持对象或者字符串,你可以把data改为List<dynamic> data; 然后重新生成
