### ISSUE TITLE
当解析的key为string时toInt是错误的

### ISSUE THREAD

**Issue by EightMinuteYouth** [zhangruiyu/FlutterJsonBeanFactory#55]
Unhandled Exception: NoSuchMethodError: Class 'String' has no instance method 'toInt'.

**Comment by zhangruiyu** [comment]
后台数据返回格式是死的  要不移动端写int 要不后台返回int  如果后台返回数据类型一直会变化,那么就是后台问题 让他们改 学会甩锅
