### ISSUE TITLE
android 混合开发 ，不能自动生成JsonConvert

### ISSUE THREAD

**Issue by Huangjiaqi0421** [zhangruiyu/FlutterJsonBeanFactory#57]
点击 Build -> FlutterBeanFactory 提示 
This project is not the flutter project or the flutterJson in pubspec.yaml with the enable set to false

**Comment by zhangruiyu** [comment]
建议加群 我没玩过混合开发  963752388

**Comment by yulongfy** [comment]
> 点击 Build -> FlutterBeanFactory 提示
> This project is not the flutter project or the flutterJson in pubspec.yaml with the enable set to false

咋解决的啊

**Comment by yulongfy** [comment]
> > 点击 Build -> FlutterBeanFactory 提示
> > This project is not the flutter project or the flutterJson in pubspec.yaml with the enable set to false
> 
> 咋解决的啊

已解决。 打开的项目根目录需要是lib的上一层，然后执行alt+j
