### ISSUE TITLE
Map类型的json，如何自动生成

### ISSUE THREAD

**Issue by bukegeshe** [zhangruiyu/FlutterJsonBeanFactory#62]
{
        "arrivalAirport3code": "FOC",
        "definitionDetails": {
            "FLEXIBLE2007141058437-Lounge_MF-Lounge": {
                "baggageAllowance": null,
                "code": "FLEXIBLE2007141058437",
                "descriptions": [],
                "flexibleProfile": null,
                "insuranceProfile": null,
                "maxQuantityPerPax": 99999,
                "mealProfile": null,
                "name": "",
                "productSubType": "Lounge_MF",
                "productType": "Lounge",
                "serviceBundle": null,
                "slogan": "",
                "ssProfile": null,
                "tags": []
            },
            "FLEXIBLE2007011348085-Lounge_MF-Lounge": {
                "baggageAllowance": null,
                "code": "FLEXIBLE2007011348085",
                "descriptions": [],
                "flexibleProfile": null,
                "insuranceProfile": null,
                "maxQuantityPerPax": 99999,
                "mealProfile": null,
                "name": "自动化回归使用-接虚拟中心-现金支付-贵宾休息室2",
                "productSubType": "Lounge_MF",
                "productType": "Lounge",
                "serviceBundle": null,
                "slogan": "",
                "ssProfile": null,
                "tags": [
                    "贵宾休息室",
                    "热卖"
                ]
            }
}
}

我尝试这样写
  Map<String,LongueEntityDefinitionDetail> definitionDetails;
自动生成的文件是这样的，报错
data.definitionDetails = new Map<String,LongueEntityDefinitionDetail>().fromJson(json['definitionDetails']);

**Comment by xuhuanli** [comment]
同样的问题

**Comment by zhangruiyu** [comment]
我这版是木得问题啊

**Comment by zhangruiyu** [comment]
已经修复了 晚上发布
