### ISSUE TITLE
Decode json with hyphen (-) char cause errors 

### ISSUE THREAD

**Issue by Carmelo992** [zhangruiyu/FlutterJsonBeanFactory#65]
I tried to decode a json generated with this link https://pokeapi.co/api/v2/pokemon/ditto 
The json contains some key with the hyphen character, the classes generated have this name PokemonSpritesVersionsGeneration-ii and this causes compiler errors. 

Moreover, in the entity helper class all the methods to convert from or two json are without the right side of the hyphen

**Comment by zhangruiyu** [comment]
This issue has been fixed and a new version is expected to be released this week
