### ISSUE TITLE
接口字段数据类型不固定带来的问题

### ISSUE THREAD

**Issue by ciscolxh** [zhangruiyu/FlutterJsonBeanFactory#67]
例入本地实体对象 
`class Test{
  int i;
}`

但是接口有时候返回map
`
{
"id":"1",
}
`
也有时候会返回
`
{
"id":1,
}
`
这就导致了在helper类解析报错
`
if (json['id'] != null) {
		data.id = json['id']?.toInt();
	}
`
这里建议将int之类(比如double)的数据改为这样解析
`
if (json['id'] != null) {
		data.id =int.tryParse(json['id'].toString());
	}
`

**Comment by zhangruiyu** [comment]
已经修复,预计晚上发版
