### ISSUE TITLE
希望能配置在项目中生成的目录

### ISSUE THREAD

**Issue by blisssayyid** [zhangruiyu/FlutterJsonBeanFactory#70]
flutter新手,感谢出了个dart2json的工具。但使用过程中没找到配置help生成的地方，希望能提供一下，否则老感觉项目结构乱了。类似于android的greendao的生成配置

**Comment by zhangruiyu** [comment]
你换mac电脑就有了 我没windows也没法跑

**Comment by blisssayyid** [comment]
![image](https://user-images.githubusercontent.com/11463194/102172158-31d50e00-3ed3-11eb-85f7-1699012e8134.png)

大哥你怎么没验证就关掉了
