### ISSUE TITLE
设计挺好的，但为啥写的这么封闭？

### ISSUE THREAD

**Issue by vecharm** [zhangruiyu/FlutterJsonBeanFactory#71]
自己想通过泛型去获取但 _fromJsonSingle 是私有，也没有fromJsonAsT(type,json) , 修改源代码 重新生成又没了

**Comment by zhangruiyu** [comment]
emmm你认真看下额


 
---原始邮件---
发件人: "VeCharm"<notifications@github.com&gt;
发送时间: 2020年11月23日 19:13:20
收件人: "zhangruiyu/FlutterJsonBeanFactory"<FlutterJsonBeanFactory@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [zhangruiyu/FlutterJsonBeanFactory] 设计挺好的，但为啥写的这么封闭？ (#71)




 
自己想通过泛型去获取但 _fromJsonSingle 是私有，也没有fromJsonAsT(type,json) , 修改源代码 重新生成又没了
