### ISSUE TITLE
是否可以添加脚本模式

### ISSUE THREAD

**Issue by xlyasdasd** [zhangruiyu/FlutterJsonBeanFactory#72]
如题用脚本执行，可以加入打包机的流程

**Comment by zhangruiyu** [comment]
不会啊

**Comment by xlyasdasd** [comment]
> 不会啊

现在因为json_convert_content.dart文件会经常冲突，被放进gitignore文件了，打包机没ide环境，得脚本执行生成json_convert_content的内容

**Comment by zhangruiyu** [comment]
json_convert_content每次拉取代码都重新生成,不需要忽略掉.也不需要处理冲突

**Comment by zhangruiyu** [comment]
json_convert_content每次拉取代码后你自己重新生成就好,不需要忽略掉.也不需要处理冲突
