### ISSUE TITLE
列表反序列异常 Another exception was thrown: type 'List<dynamic>' is not a subtype of type ...

### ISSUE THREAD

**Issue by blisssayyid** [zhangruiyu/FlutterJsonBeanFactory#74]
在 list 序列化为对象时报错： `Another exception was thrown: type 'List<dynamic>' is not a subtype of type 'List<XXX>' in type cast`

发现在 `json_convert_content.dart` 文件中列表序列化方式：`return data.map((e) => XXX().fromJson(e)).toList() as M;`

建议改为 `return data.map<XXX>((e) => XXX().fromJson(e)).toList() as M;`

**Comment by zhangruiyu** [comment]
好的 已经修复了 感谢反馈  预计晚上发新版本
