### ISSUE TITLE
Getting Unhandled Exception while parsing

### ISSUE THREAD

**Issue by dipakbari4** [zhangruiyu/FlutterJsonBeanFactory#79]
`var myClassInstance = JsonConvert<MyDataClass>().fromJson(jsonMapped);`

Unhandled Exception: _type `'JsonConvert<MyDataClass>'` is not a subtype of type `'MyDataClass'` in type cast_

**Comment by zhangruiyu** [comment]
you should use " JsonConvert.fromJsonAsT<MyDataClass>(json) "

**Comment by dipakbari4** [comment]
It's still not working at my side.
Can you demonstrate using [this](https://jsonplaceholder.typicode.com/todos) API?
Thank you.

**Comment by zhangruiyu** [comment]
please give me a complete example,So far I don't know what the problem is

**Comment by zhangruiyu** [comment]
![image](https://user-images.githubusercontent.com/10591822/111446821-c1df5980-8747-11eb-9ff2-4eadcf39f616.png)
It has been tested and there is no problem. You should use List<>

**Comment by dipakbari4** [comment]
Hi,
Thanks for replying again.
Where do you get from the `json.decode(d)`?

I'm using it like passing the response body [json] into the function parameter:

```dart
var todos = JsonConvert.fromJsonAsT<List<TodoEntity>>(response.body);
```

It'd be great if you share gist /  source code of the above given example.

Thanks.

**Comment by dipakbari4** [comment]
Okay, I got it.
It solved now.
```dart
var todos = JsonConvert.fromJsonAsT<List<TodoEntity>>(jsonDecode(response.body));
```
Thanks.
