### ISSUE TITLE
flutter2.0 List 默认构造方法被标记弃用了 default constructor has been marked deprecated in flutter2.0

### ISSUE THREAD

**Issue by kvii2202** [zhangruiyu/FlutterJsonBeanFactory#81]
如图
![image](https://user-images.githubusercontent.com/56432636/110062960-38be3f00-7da5-11eb-8c82-3b1518257bd4.png)
可以改为
``` dart
final not    = List<AAA>();  // ×
final should = <AAA>[];      // √
```

**Comment by zhangruiyu** [comment]
预计周末之前支持2.0所有新东西 请等待下吧

**Comment by zhangruiyu** [comment]
可以加下qq群: 963752388  我给你发新版本 已经支持null safety了 还有list的构造
