### ISSUE TITLE
4.0 紧急bug 

### ISSUE THREAD

**Issue by prczhb** [zhangruiyu/FlutterJsonBeanFactory#82]
![image](https://user-images.githubusercontent.com/26354648/110311936-69b9a080-803f-11eb-953e-31ef98f5b820.png)

如图 下面部分是3.7.6生成的 上图是4.0生成的
4.0中 A?.map((v) => v.toJson()).toList();   map前面做了判断  但是后面的.tolist 没有判断 ,导致解析失败
3.7.6 直接通过判空跳过的

4.0
```
	data['offlineChannels'] =  entity.offlineChannels?.map((v) => v.toJson()).toList();
```

3.7.6 
```
	if (entity.offlineChannels != null) {
		data['offlineChannels'] =  entity.offlineChannels.map((v) => v.toJson()).toList();
	}
```

**Comment by zhangruiyu** [comment]
后面漏了个？吧。我明天给加上


 
---原始邮件---
发件人: "prczhb"<notifications@github.com&gt;
发送时间: 2021年3月8日 18:55:28
收件人: "zhangruiyu/FlutterJsonBeanFactory"<FlutterJsonBeanFactory@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [zhangruiyu/FlutterJsonBeanFactory] 4.0 紧急bug  (#82)




 

 
如图 下面部分是3.7.6生成的 上图是4.0生成的
 4.0中 A?.map((v) =&gt; v.toJson()).toList();   map前面做了判断  但是后面的.tolist 没有判断 ,导致解析失败
 3.7.6 直接通过判空跳过的
 
4.0
 data['offlineChannels'] =  entity.offlineChannels?.map((v) =&gt; v.toJson()).toList();  
3.7.6
 if (entity.offlineChannels != null) { data['offlineChannels'] =  entity.offlineChannels.map((v) =&gt; v.toJson()).toList(); }
