### ISSUE TITLE
Datetime转换问题

### ISSUE THREAD

**Issue by limebinary** [zhangruiyu/FlutterJsonBeanFactory#83]
假设一个属性名称是updateTime，类型是Datetime。

3.7.6版本生成的helper是这样转换的：
data.updateTime = DateTime.tryParse(json['updateTime']);

4.0.0版本后生成的helper变成这样：
data.updateTime = json['updateTime'];

导致在更新4.0.x后，helper在运行时会抛出 type'string' is not a subtype of type'datetime'异常。

请帮忙解决，感谢。

**Comment by zhangruiyu** [comment]
已经更新了

**Comment by zhangruiyu** [comment]
升级4.0.2即可
