### ISSUE TITLE
Error: kotlin.KotlinNullPointerException

### ISSUE THREAD

**Issue by kvii2202** [zhangruiyu/FlutterJsonBeanFactory#85]
### plugin version:
![image](https://user-images.githubusercontent.com/56432636/111268019-b3ba0c00-8667-11eb-9e11-1f2afdc92975.png)

### Android Studio version:
![image](https://user-images.githubusercontent.com/56432636/111268647-7e61ee00-8668-11eb-9350-8e108fb1dbee.png)

### flutter version:
`[✓] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19043.867], locale zh-CN)`

### 报错信息:
> kotlin.KotlinNullPointerException at com.ruiyu.dart_to_helper.node.GeneratorDartClassNodeToHelperInfo.getDartFileHelperClassGeneratorInfo(**GeneratorDartClassNodeToHelperInfo.kt:109**)
	at com.ruiyu.file.FileHelpers.getAllEntityFiles(FileHelpers.kt:159)
	at com.ruiyu.beanfactory.FlutterBeanFactoryAction$Companion.generateAllFile(FlutterBeanFactoryAction.kt:34)
	at com.ruiyu.beanfactory.FlutterBeanFactoryAction.actionPerformed(FlutterBeanFactoryAction.kt:21)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:280)
...

### 源代码
``` kotlin
/**
 * 获取所有符合生成的file
 */
fun getAllEntityFiles(project: Project): List<Pair<HelperFileGeneratorInfo, String>> {
    val pubSpecConfig = getPubSpecConfig(project)
    val psiManager = PsiManager.getInstance(project)
    return FilenameIndex.getAllFilesByExt(project, "dart").filter {
        //不过滤entity结尾了
        /*it.path.endsWith("_${ServiceManager.getService(Settings::class.java).state.modelSuffix.toLowerCase()}.dart") && */it.path.contains("${project.name}/lib/")
    }.mapNotNull {
       // 👇 应该是这里
        val dartFileHelperClassGeneratorInfo = GeneratorDartClassNodeToHelperInfo.getDartFileHelperClassGeneratorInfo(psiManager.findFile(it)!!)

        //导包
        if (dartFileHelperClassGeneratorInfo == null) {
            null
        } else {
            //包名
            val packageName = (it.path).substringAfter("${project.name}/lib/")
            dartFileHelperClassGeneratorInfo to "import 'package:${pubSpecConfig?.name}/${packageName}';"
        }

    }
}
```

**Comment by kvii2202** [comment]
忘记说了，我的工程没有配置 NullSafety。

**Comment by zhangruiyu** [comment]
0-0我没法解决windows上问题额

**Comment by zhangruiyu** [comment]
你可以给clone下来 然后自己debug下看看哪里问题

**Comment by zhangruiyu** [comment]
和null safety没关系的

**Comment by zhangruiyu** [comment]
我想已经解决了 应该是新版本为var支持的不好导致的 请更新到4.0.6
