### ISSUE TITLE
不支持在插件和module中使用

### ISSUE THREAD

**Issue by shingohu** [zhangruiyu/FlutterJsonBeanFactory#89]
RT

**Comment by zhangruiyu** [comment]
idea|as 打开项目的根目录必须包含pubspec.yaml,子目录必须包含lib,此刻才能去生成

**Comment by shingohu** [comment]
新版本是不是不支持extends JsonConvert,只能用with了,昨天更新alt+j后发现删除了好多生成的helper,立马感觉不对,在去查看发现是extends JsonConvert的entity的helper全被删了,要哭了

**Comment by zhangruiyu** [comment]
你加群吧，到公司就发新版本。支持extends


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月21日 08:34:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhangruiyu/FlutterJsonBeanFactory] 不支持在插件和module中使用 (#89)




 
新版本是不是不支持extends JsonConvert,只能用with了,昨天更新alt+j后发现删除了好多生成的helper,立马感觉不对,在去查看发现是extends JsonConvert的entity的helper全被删了,要哭了
